language: generic
sudeo: required 
services:
  - docker
before_install:
  - docker build -t jaisuriya/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jaisuriya/docker-react npm run test